### ISSUE TITLE
forget to copy policy to policy_old during ppo initialization?

### ISSUE THREAD

**Issue by YilunZhou** [nikhilbarhate99/PPO-PyTorch#10]
Should there be a `self.policy_old.load_state_dict(self.policy.state_dict())` on line 85 of `PPO.py`, after the initialization of PPO object? PyTorch random initialization does not guarantee that these two policies will be the same. And the same issue for `PPO_continuous.py`.

**Comment by nikhilbarhate99** [comment]
Thanks !
