### ISSUE TITLE
Unexpected key(s) in state_dict: "affine.weight", "affine.bias". 

### ISSUE THREAD

**Issue by fatalfeel** [nikhilbarhate99/PPO-PyTorch#32]
/usr/bin/python3 /root/PycharmProjects/PPO-PyTorch/test.py
Traceback (most recent call last):
  File "/root/PycharmProjects/PPO-PyTorch/test.py", line 36, in <module>
    ppo.policy_old.load_state_dict(torch.load(pathfile))
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ActorCritic:
	Unexpected key(s) in state_dict: "affine.weight", "affine.bias". 

    #ppo.policy_old.load_state_dict(torch.load(directory+filename))
    loadweight = torch.load(pathfile)
    ppo.policy_old.load_state_dict(loadweight)   //////-> crash here

**Comment by fatalfeel** [comment]
ppo.policy_old.load_state_dict(torch.load(pathfile),strict=False)

~after add strict=False then ok

**Comment by outdoteth** [comment]
Lifesaver thanks. @fatalfeel
