### ISSUE TITLE
Question on multiple actors

### ISSUE THREAD

**Issue by pengzhi1998** [nikhilbarhate99/PPO-PyTorch#34]
Hi @nikhilbarhate99, thank you for your great work!
However, I found in your Readme that: `Number of actors for collecting experience = 1. This could be easily changed by creating multiple instances of ActorCritic networks in the PPO class and using them to collect experience (like A3C and standard PPO).`
But how to change it? What should I modify for the gradient ascent part if there are multiple actors in parallel?
Thank you for your help!

**Comment by nikhilbarhate99** [comment]
I am not sure how other repos implement parallel RL (If you want robust and working code, I would suggest you use existing implementations like [RLLib](https://docs.ray.io/en/master/rllib.html) or [Ilya Kostrikov's repo](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail)). 

A simplistic approach would be:
1. Initialize a `shared_policy` with random weights
2. Create and Run N new instances of the policy (all having same weights as `shared policy`) in N env instances (i.e. 1 policy instance in 1 env instance) in parallel. In each instance collect the experience (one or many episodes per instance) and calculate returns (with Monte Carlo or GAE or Bootstrapping etc.) and store it in a `shared_buffer`.
4. Update the `shared_policy` weights with experience in `shared_buffer`.
5. Jump to step 2

EDIT: one of the [forks](https://github.com/rhklite/Parallel-PPO-PyTorch) of this repo has been modified to a parallel implementation.

**Comment by pengzhi1998** [comment]
Thank you very much! I'll take a look.
