### ISSUE TITLE
The reward function for training?

### ISSUE THREAD

**Issue by DongXingshuai** [nikhilbarhate99/PPO-PyTorch#45]
Hi, thanks for your open-source code. Can you tell me which reward function that is used for training? Thanks again.

**Comment by nikhilbarhate99** [comment]
Hi, I do not know how the rewards are calculated exactly, for that you will have to go through the code of roboschool env (for example: [link](https://github.com/openai/roboschool/blob/master/roboschool/gym_forward_walker.py#L119)).

Although rewards are important for RL, most of the RL research is based on standard benchmarks and abstract away the reward function as an black box function that needs to be optimized.
