### ISSUE TITLE
How to improve the performance based on your code?

### ISSUE THREAD

**Issue by 4thfever** [nikhilbarhate99/PPO-PyTorch#48]
Hi

Thanks for your code sharing and your nice work!

I trained the agent on CartPole task and it works well. However, my agent and your agent are not perfect yet (sometimes the reward is less than 400). I guess this comes from your code's minimalism.

`Episode: 1 		 Reward: 400.0
Episode: 2 		 Reward: 400.0
Episode: 3 		 Reward: 400.0
Episode: 4 		 Reward: 126.0
Episode: 5 		 Reward: 400.0`

I am wondering what is the recommended way or trick to improve my agent's performance based on your code?

Thanks a lot

**Comment by nikhilbarhate99** [comment]
Since the environment and policy are stochastic, it cannot be guaranteed that the agent will be successful in every episode.

To further improve, you can try to train it for longer time and decreasing the min_action_std, so it is less random at the end.
