### ISSUE TITLE
The `ppo_continuous.py` model does not learn  

### ISSUE THREAD

**Issue by chingandy** [nikhilbarhate99/PPO-PyTorch#5]
Thank you for sharing your ppo implementation on this repository. 

However, I have tried to run your code `ppo_continuous.py` and I figured that the average reward was not increasing at all. Doesn't that mean the model is not learning?

**Comment by nikhilbarhate99** [comment]
Hey, I updated the repo with a bug fix. Try again and let me know.

**Comment by chingandy** [comment]
Now the model seems to work now. Thank you for your update.
