### ISSUE TITLE
About environment configuration

### ISSUE THREAD

**Issue by BIT-KaiYu** [nikhilbarhate99/PPO-PyTorch#50]
Hello, I am very interested in your work. I would like to ask about your specific environment configuration, such as python, gym, roboschool, etc.

**Comment by nikhilbarhate99** [comment]
Environment configuration (setup in colab notebook): 
roboschool 1.0.48 
gym 0.15.4

**Comment by Jose-Escamilla** [comment]
apparently that version of roboscool is not available, do you know how to fix it?
