### ISSUE TITLE
Convolutional?

### ISSUE THREAD

**Issue by Bobingstern** [nikhilbarhate99/PPO-PyTorch#51]
I want to use this for Atari games but I'm unsure about how to change it to use CNN layers. Can I just literally change the actor and critic models to have a Conv2d layer or do I need to change the replay buffer for multi-dimensional arrays?

**Comment by nikhilbarhate99** [comment]
You might have to (not sure) change the buffer to handle the images and add Conv2d layers in the actor and critic models.
Also to get RL algos (which have not been tested on atari) to train on atari takes quite a bit of work.

You can still first try it on a simple atari game like pong or on another similar env like [minAtar](https://github.com/kenjyoung/MinAtar)

Also you can use some tricks like passing the difference of observation images to the model. 
refer to [Andrej Karpathys blog on Deep RL for pong](https://karpathy.github.io/2016/05/31/rl/) ... although he implements everything from scratch you can use PyTorch and try to use the same tricks.

**Comment by nihao-zhangtongxue** [comment]
I try it, but got bad traing
