### ISSUE TITLE
Implementation issues

### ISSUE THREAD

**Issue by kierkegaard13** [nikhilbarhate99/PPO-PyTorch#6]
I'm a bit new to PPO, but I think this line is out of place in PPO.py:

```
123        self.policy_old.load_state_dict(self.policy.state_dict())
```

I think it should be placed before the for loop, because otherwise policy and policy_old will be identical and the log probs should evaluate to the same value.

**Comment by nikhilbarhate99** [comment]
The `policy` and `policy_old` will be identical for the first iteration of the update loop. At the end of the iteration we update the `policy` and not `policy_old`, so in further iterations they are not identical. After performing `K` updates the updated `policy` is loaded into `policy_old`.

Refer to [PPO](https://stackoverflow.com/questions/46422845/what-is-the-way-to-understand-proximal-policy-optimization-algorithm-in-rl)

**Comment by kierkegaard13** [comment]
Cool, I think I see now. Thanks for the link.
